services:
  - type: web
    name: Multi_Agent_Report_Generator
    env: python
    region: oregon
    runtime: python-3.11.0
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
